import fs from "node:fs";
import { pathToFileURL } from "node:url";
import { parseArgs } from "./records.mjs";
import { commentRanges } from "./count.mjs";

const DEFAULT_MAX = 3;

// A percentage alone forbids CLAUDE.md's sanctioned comments outright in a
// small file: 3% of 30 lines is zero, so one `TODO(#238)` reds the gate. The
// floor is what lets the two rules coexist.
const FLOOR_LINES = 2;

const DIRECTIVE =
  /^(eslint-(disable|enable)|@ts-(expect-error|ignore|nocheck)|#__PURE__|<reference\b|prettier-ignore|[cv]8 ignore|istanbul ignore|@vitest-environment|impeccable-(disable|ignore))/;

function isDirective(line) {
  const text = line.trim();
  return DIRECTIVE.test(text.replace(/^\s*(\/\/+|\/\*+|\*+\/?)\s*/, ""));
}

const GENERATED = /@generated|GENERATED FILE|should not be edited|Generated by/;

export function isGenerated(text) {
  return GENERATED.test(text.split("\n").slice(0, 8).join("\n"));
}

export function allowance(total, max = DEFAULT_MAX) {
  return Math.max(FLOOR_LINES, Math.floor((max * total) / 100));
}

export function density(file, text = fs.readFileSync(file, "utf8")) {
  const { ranges } = commentRanges(file, text);
  const lines = text.split("\n");
  const starts = [];
  let p = 0;
  for (const l of lines) {
    starts.push(p);
    p += l.length + 1;
  }
  const mask = new Uint8Array(text.length);
  for (const [a, b] of ranges) for (let i = a; i < b; i++) mask[i] = 1;
  let budgeted = 0;
  let directives = 0;
  for (let i = 0; i < lines.length; i++) {
    const s = starts[i];
    const e = s + lines[i].length;
    let hasComment = false;
    let hasCode = false;
    for (let j = s; j < e; j++) {
      if (text[j].trim() === "") continue;
      if (mask[j]) hasComment = true;
      else hasCode = true;
    }
    if (!hasComment || hasCode) continue;
    if (isDirective(lines[i])) directives++;
    else budgeted++;
  }
  const total = lines.length - (lines.at(-1) === "" ? 1 : 0);
  return {
    budgeted,
    directives,
    total,
    pct: total ? (100 * budgeted) / total : 0,
  };
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const argv = process.argv.filter((a, i) => {
    if (a === "--max") return false;
    return process.argv[i - 1] !== "--max";
  });
  const maxArg = process.argv[process.argv.indexOf("--max") + 1];
  const max = process.argv.includes("--max") ? Number(maxArg) : DEFAULT_MAX;
  if (!Number.isFinite(max)) {
    console.error("density.mjs: --max needs a number");
    process.exit(2);
  }
  const { files } = parseArgs(argv, "density.mjs", false);
  let overBudget = 0;
  let totB = 0;
  let totL = 0;
  let skipped = 0;
  const rows = [];
  for (const f of files) {
    let r;
    try {
      const text = fs.readFileSync(f, "utf8");
      if (isGenerated(text)) {
        skipped++;
        console.log("   -  (generated; its header is its generator's)  " + f);
        continue;
      }
      r = density(f, text);
    } catch {
      skipped++;
      console.log("   -  (absent from the working tree)  " + f);
      continue;
    }
    totB += r.budgeted;
    totL += r.total;
    const allowed = allowance(r.total, max);
    const over = r.budgeted > allowed;
    if (over) overBudget++;
    rows.push({ f, ...r, over, excess: r.budgeted - allowed });
  }
  rows.sort((a, b) => b.excess - a.excess);
  for (const r of rows) {
    console.log(
      `${r.over ? "OVER" : "  ok"} ${String(r.budgeted).padStart(4)}/${String(r.total).padStart(4)} = ${r.pct.toFixed(1).padStart(5)}%  cut ${String(Math.max(0, r.excess)).padStart(4)}  ${r.f}`,
    );
  }
  const pct = totL ? (100 * totB) / totL : 0;
  console.log(
    `TOTAL ${totB}/${totL} = ${pct.toFixed(1)}%  budget ${max}% or ${FLOOR_LINES} lines, whichever is larger  ${overBudget} of ${rows.length} files OVER` +
      (skipped ? `; ${skipped} of ${files.length} SKIPPED` : ""),
  );
  if (skipped === files.length) process.exit(2);
  if (overBudget) process.exit(1);
}
