import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { execFileSync } from "node:child_process";
import {
  classifyLine,
  commentRanges,
  lineStarts,
  maskOf,
  parseArgs,
} from "./count.mjs";

const DEFAULT_MAX = 3;

// A floor, not slack — see ADR-0075.
const FLOOR_LINES = 2;

export const repoRoot = path.resolve(import.meta.dirname, "..", "..");

// The one list — see ADR-0075.
export const DIRECTIVES = [
  [
    "eslint-disable",
    /^eslint-disable/,
    "// eslint-disable-next-line no-x -- why",
  ],
  ["eslint-enable", /^eslint-enable/, "/* eslint-enable no-x */"],
  ["@ts-expect-error", /^@ts-expect-error/, "// @ts-expect-error deliberate"],
  ["@ts-ignore", /^@ts-ignore/, "// @ts-ignore legacy"],
  ["@ts-nocheck", /^@ts-nocheck/, "// @ts-nocheck"],
  ["#__PURE__", /^#__PURE__/, "/*#__PURE__*/"],
  ["/// <reference", /^<reference\b/, '/// <reference types="next" />'],
  ["prettier-ignore", /^prettier-ignore/, "// prettier-ignore"],
  [
    "impeccable-disable",
    /^impeccable-disable/,
    "// impeccable-disable-next-line side-tab",
  ],
  ["impeccable-ignore", /^impeccable-ignore/, "// impeccable-ignore side-tab"],
  [
    "@vitest-environment",
    /^@vitest-environment/,
    "// @vitest-environment node",
  ],
  ["c8 ignore", /^c8 ignore/, "/* c8 ignore next */"],
  ["v8 ignore", /^v8 ignore/, "/* v8 ignore next */"],
  ["istanbul ignore", /^istanbul ignore/, "/* istanbul ignore next */"],
];

function isDirective(line) {
  const text = line.trim().replace(/^\s*(\/\/+|\/\*+|\*+\/?)\s*/, "");
  return DIRECTIVES.some(([, pattern]) => pattern.test(text));
}

const GENERATED = /@generated|GENERATED FILE|should not be edited|Generated by/;

export function isGenerated(text) {
  return GENERATED.test(text.split("\n").slice(0, 8).join("\n"));
}

// The corpus, defined once — see ADR-0075. `-z` because a newline in a
// filename splits into two unreadable paths, and unreadable is SKIPPED.
export function trackedFiles() {
  return execFileSync(
    "git",
    ["ls-files", "-z", "*.ts", "*.tsx", "*.mts", "*.cts", "*.mjs", "*.cjs"],
    { encoding: "utf8", cwd: repoRoot },
  )
    .split("\0")
    .filter((f) => f && !f.startsWith(".claude/skills/"));
}

export function allowance(total, max = DEFAULT_MAX) {
  return Math.max(FLOOR_LINES, Math.floor((max * total) / 100));
}

export function density(file, text = fs.readFileSync(file, "utf8")) {
  const { ranges } = commentRanges(file, text);
  const lines = text.split("\n");
  const starts = lineStarts(text, lines);
  const mask = maskOf(text, ranges);
  let budgeted = 0;
  let directives = 0;
  for (let i = 0; i < lines.length; i++) {
    const s = starts[i];
    const { hasComment, hasCode } = classifyLine(
      text,
      mask,
      s,
      s + lines[i].length,
    );
    if (!hasComment || hasCode) continue;
    if (isDirective(lines[i])) directives++;
    else budgeted++;
  }
  const total = lines.length - (lines.at(-1) === "" ? 1 : 0);
  return {
    budgeted,
    directives,
    total,
    pct: total ? (100 * budgeted) / total : 0,
  };
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const argv = process.argv.filter((a, i) => {
    if (a === "--max" || a === "--tracked") return false;
    return process.argv[i - 1] !== "--max";
  });
  const maxArg = process.argv[process.argv.indexOf("--max") + 1];
  const max = process.argv.includes("--max") ? Number(maxArg) : DEFAULT_MAX;
  if (!Number.isFinite(max)) {
    console.error("density.mjs: --max needs a number");
    process.exit(2);
  }
  let files;
  if (process.argv.includes("--tracked")) {
    process.chdir(repoRoot);
    files = trackedFiles();
  } else {
    ({ files } = parseArgs(argv, "density.mjs"));
  }
  let overBudget = 0;
  let totB = 0;
  let totL = 0;
  let skipped = 0;
  const rows = [];
  for (const f of files) {
    let r;
    try {
      const text = fs.readFileSync(f, "utf8");
      if (isGenerated(text)) {
        skipped++;
        console.log("   -  (generated; its header is its generator's)  " + f);
        continue;
      }
      r = density(f, text);
    } catch {
      skipped++;
      console.log("   -  (absent from the working tree)  " + f);
      continue;
    }
    totB += r.budgeted;
    totL += r.total;
    const allowed = allowance(r.total, max);
    const over = r.budgeted > allowed;
    if (over) overBudget++;
    rows.push({ f, ...r, over, excess: r.budgeted - allowed });
  }
  rows.sort((a, b) => b.excess - a.excess);
  for (const r of rows) {
    console.log(
      `${r.over ? "OVER" : "  ok"} ${String(r.budgeted).padStart(4)}/${String(r.total).padStart(4)} = ${r.pct.toFixed(1).padStart(5)}%  cut ${String(Math.max(0, r.excess)).padStart(4)}  ${r.f}`,
    );
  }
  const pct = totL ? (100 * totB) / totL : 0;
  console.log(
    `TOTAL ${totB}/${totL} = ${pct.toFixed(1)}%  budget ${max}% or ${FLOOR_LINES} lines, whichever is larger  ${overBudget} of ${rows.length} files OVER` +
      (skipped ? `; ${skipped} of ${files.length} SKIPPED` : ""),
  );
  if (skipped === files.length) process.exit(2);
  if (overBudget) process.exit(1);
}
