import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { count, commentRanges } from "./count.mjs";
import {
  allowance,
  density,
  DIRECTIVES,
  isGenerated,
  repoRoot,
  trackedFiles,
} from "./density.mjs";

process.chdir(repoRoot);

const dir = fs.mkdtempSync(path.join(os.tmpdir(), "comment-audit-"));
process.on("exit", () => fs.rmSync(dir, { recursive: true, force: true }));
const write = (name, text) => {
  const p = path.join(dir, name);
  fs.writeFileSync(p, text);
  return p;
};

let failed = 0;
const check = (label, actual, expected) => {
  const ok = JSON.stringify(actual) === JSON.stringify(expected);
  if (!ok) failed++;
  console.log(
    `${ok ? "ok  " : "FAIL"}  ${label}${ok ? "" : `  expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`}`,
  );
};

const run = (args) => {
  try {
    return {
      code: 0,
      out: execFileSync("node", args, { encoding: "utf8", stdio: "pipe" }),
    };
  } catch (e) {
    return { code: e.status, out: (e.stdout ?? "") + (e.stderr ?? "") };
  }
};
const tool = (n) => path.join(import.meta.dirname, n);

check(
  "template literals do not hide later comments",
  commentRanges(
    write(
      "tpl.ts",
      "// one\nconst a = `x${1}y`;\n// two\nconst b = 1;\n// three\n",
    ),
  ).ranges.length,
  3,
);

check(
  "a whitespace-only line inside a block is not a comment line",
  count(write("ws.ts", "/*\n   \n * hi\n */\nconst a = 1;\n")).commentOnly,
  3,
);

check(
  "a zero-length line inside a block is not a comment line either",
  count(write("ws2.ts", "/*\n\n * hi\n */\nconst a = 1;\n")).commentOnly,
  3,
);

check("total matches wc -l", count(write("n.ts", "const a = 1;\n")).total, 1);
check("an empty file has no lines", count(write("e.ts", "")).total, 0);
check(
  "a file with no comments counts none",
  count(write("c.ts", "const a = 1;\n")).commentOnly,
  0,
);
check(
  "CRLF is handled",
  count(write("crlf.ts", "// hi\r\nconst a = 1;\r\n")).commentOnly,
  1,
);

check(
  "a .tsx file sees its JSX comments",
  commentRanges(
    write(
      "j.tsx",
      "export const A = () => (\n  <div>\n    {/* hi */}\n  </div>\n);\n",
    ),
  ).ranges.length,
  1,
);

check(
  "a JSX comment line is budgeted, braces and all",
  density(
    write(
      "jsx-prose.tsx",
      "export const A = () => (\n  <div>\n    {/* one */}\n    {/* two */}\n  </div>\n);\n",
    ),
  ).budgeted,
  2,
);

check(
  "a multi-line JSX comment is budgeted on every line",
  density(
    write(
      "jsx-block.tsx",
      "export const A = () => (\n  <div>\n    {/* one\n        two */}\n  </div>\n);\n",
    ),
  ).budgeted,
  2,
);

check(
  "a trailing brace with a trailing comment stays a code line",
  density(write("brace.ts", "const a = {\n  b: 1,\n}; // trailing\n")).budgeted,
  0,
);

check(
  "a trailing `//` anchor sits on a code line and is not budgeted",
  density(write("anchor.ts", "const a = [\n  [1, 0], //\n];\n")).budgeted,
  0,
);

check(
  "a standalone `//` is residue and IS budgeted",
  density(write("residue.ts", "const a = [\n  //\n  1,\n];\n")).budgeted,
  1,
);

const densityFixture = write(
  "density-fixture.ts",
  [
    "// a budgeted prose line",
    "// a second budgeted prose line",
    "// a third, which puts the fixture past the 2-line floor",
    "// eslint-disable-next-line no-console -- the reason is part of the directive",
    "/*#__PURE__*/",
    "// @ts-expect-error deliberate",
    "export const a = 1;",
    "export const b = 2;",
  ].join("\n") + "\n",
);
check("density counts prose only", density(densityFixture).budgeted, 3);

check("density exempts directives", density(densityFixture).directives, 3);
check("density total is wc -l", density(densityFixture).total, 8);
check(
  "density pct is prose over total",
  Number(density(densityFixture).pct.toFixed(2)),
  37.5,
);
check(
  "a file over budget exits 1",
  run([tool("density.mjs"), densityFixture]).code,
  1,
);
check(
  "the same file under a loose budget exits 0",
  run([tool("density.mjs"), "--max", "50", densityFixture]).code,
  0,
);

check(
  "a generated header is recognised (next-env.d.ts)",
  isGenerated(
    '/// <reference types="next" />\n\n// NOTE: This file should not be edited\n',
  ),
  true,
);
check(
  "a generated header is recognised (rendered word list)",
  isGenerated("// GENERATED FILE - do not edit.\nexport const A = 1;\n"),
  true,
);
check(
  "ordinary prose is not mistaken for a generated header",
  isGenerated(
    "// The worker bound lives once, at the repo root.\nexport const a = 1;\n",
  ),
  false,
);
// A SKIPPED file is never measured, and `isGenerated` is a substring test —
// so `// Generated by hand` in a header is a self-service exemption from the
// gate. Pinning the set is what makes adding a fourth a visible decision.
{
  const skipped = run([tool("density.mjs"), ...trackedFiles()])
    .out.split("\n")
    .filter((l) => l.includes("(generated;"))
    .map((l) =>
      l
        .trim()
        .split(/\s{2,}/)
        .at(-1),
    )
    .sort();
  check("exactly these files skip the budget as generated", skipped, [
    "apps/api/next-env.d.ts",
    "apps/web/next-env.d.ts",
    "packages/games/src/termo/words.generated.ts",
  ]);
}

check(
  "a generated marker far down the file does not exempt it",
  isGenerated("\n".repeat(12) + "// @generated\n"),
  false,
);

// The corpus is the gate's whole reach: one more filter here and every check
// below still prints green over nothing. See ADR-0075.
{
  const files = trackedFiles();
  const ext = (e) => files.some((f) => f.endsWith(e));
  check(
    "the corpus spans every extension the budget claims",
    [".ts", ".tsx", ".mjs"].map(ext),
    [true, true, true],
  );
  check(
    "the corpus reaches the apps, the packages and the repo root",
    [
      files.some((f) => f.startsWith("apps/")),
      files.some((f) => f.startsWith("packages/")),
      files.some((f) => !f.includes("/")),
    ],
    [true, true, true],
  );
  check(
    "vendored skills are the only exclusion",
    files.filter((f) => f.startsWith(".claude/skills/")).length,
    0,
  );
  check("the corpus is not a rounding error", files.length > 400, true);
}

for (const [label, , example] of DIRECTIVES) {
  const probe = write(
    `exempt-${label.replaceAll(/\W/g, "")}.ts`,
    `${example}\nexport const a = 1;\n`,
  );
  check(`density exempts ${label}`, density(probe).budgeted, 0);
}

// The probes are driven off the array, so a DELETED member takes its own probe
// with it. These two read the prose instead: the budget is only enforceable if
// the documented exempt set and the live one are the same set.
{
  const documented = (file, lead) => {
    const line = fs
      .readFileSync(file, "utf8")
      .split("\n")
      .find((l) => l.startsWith(lead));
    return line === undefined
      ? ["<no line starting: " + lead + ">"]
      : [...line.matchAll(/`([^`]+)`/g)].map((m) => m[1]).sort();
  };
  const live = DIRECTIVES.map(([label]) => label).sort();
  check(
    "the exempt set is exactly what CLAUDE.md enumerates",
    documented("CLAUDE.md", "Directives are exempt and never counted:"),
    live,
  );
  check(
    "the exempt set is exactly what the README enumerates",
    documented(
      "scripts/comment-audit/README.md",
      "Directives are exempt and never counted:",
    ),
    live,
  );
}

check(
  "a real file's `@vitest-environment` stays exempt",
  density("apps/web/test/og-image.node.test.ts").directives >= 1,
  true,
);

check(
  "prose that merely mentions a directive is NOT exempt",
  density(
    write(
      "mentions.ts",
      "// see the /*#__PURE__*/ above\nexport const a = 1;\n",
    ),
  ).budgeted,
  1,
);

// A percentage alone forbids CLAUDE.md's sanctioned comments in a small file:
// 3% of 30 lines is zero, so one `TODO(#238)` would red the gate.
check("a small file gets a floor of 2 lines", allowance(4), 2);
check("the floor does not apply once 3% exceeds it", allowance(1000), 30);
check("the allowance rounds down, not up (67 lines)", allowance(67), 2);
check("the allowance rounds down, not up (101 lines)", allowance(101), 3);
check(
  "a file exactly at its allowance is within budget",
  run([
    tool("density.mjs"),
    write(
      "boundary.ts",
      ["// one", "// two", "// three"]
        .concat(
          Array.from({ length: 97 }, (_, i) => `export const v${i} = ${i};`),
        )
        .join("\n") + "\n",
    ),
  ]).code,
  0,
);
check(
  "one sanctioned TODO in a 4-line file is within budget",
  run([
    tool("density.mjs"),
    write("todo.ts", "// TODO(#238): see the issue\nexport const a = 1;\n"),
  ]).code,
  0,
);
check(
  "three prose lines in a 4-line file are not",
  run([
    tool("density.mjs"),
    write("prose.ts", "// one\n// two\n// three\nexport const a = 1;\n"),
  ]).code,
  1,
);

check(
  "a non-numeric --max exits 2",
  run([tool("density.mjs"), "--max", "lots", densityFixture]).code,
  2,
);

for (const t of ["count", "density"]) {
  check(`${t}.mjs refuses an empty file list`, run([tool(`${t}.mjs`)]).code, 2);
}

console.log(
  failed === 0 ? "\nall checks passed" : `\n${failed} check(s) FAILED`,
);
process.exit(failed === 0 ? 0 : 1);
